
function Get-FullPath {
    <#
    .SYNOPSIS
        Expands TestDrive:/ links to full paths
        some functions don't support TestDrive-style paths
        generated by Pester

    .EXAMPLE
        Get-FullPath 'TestDrive:/subfolder/file.txt'
    #>
    [CmdletBinding()]
    param (
        [Parameter(Mandatory, Position = 0)]
        [string]
        $path,

        [Parameter(Position = 1)]
        [string]
        $drive = 'TestDrive'
    )

    process {
        $path.Replace("$drive`:", (Get-PSDrive $drive).Root)
    }
}
